### PR TITLE
GHC HEAD compat.

### PR DESCRIPTION
**Pull request by mboes**

### CODE REVIEW

**Comment by nomeata** [comment]
Thanks. Can you add the necessary `ifdefs` so that it works with previous versions as well?

**Comment by FranklinChen** [comment]
Cool, a fixed ghc-heap-view will enable me to update ghc-vis https://github.com/def-/ghc-vis/issues/13

**Comment by mboes** [comment]
@nomeata ok fair enough I've retained `IND_PERM` in prior versions of GHC.

**Comment by nomeata** [comment]
Thanks!

**Comment by nomeata** [comment]
Hi @mboes, this change to HEAD should probably be reflected here as well. Would you care to have a look again?
https://phabricator.haskell.org/D2690

**Pull request merged**
