### PR TITLE
Add basic support for building with GHC 8.6

### PR DESCRIPTION
**Pull request by intricate**

### CODE REVIEW

**Comment by erikd** [comment]
@nomeata This contributor is a colleague of mine and we would like to use this in a test suite.

**Comment by nomeata** [comment]
You write “basic” support – what’s basic about it.

Also, GHC-8.6 ships with `ghc-heap` which does these things more proper. Shouldn’t you rather use that library?

**Comment by intricate** [comment]
@nomeata 
> You write “basic” support – what’s basic about it.
> 
> Also, GHC-8.6 ships with `ghc-heap` which does these things more proper. Shouldn’t you rather use that library?

Appreciate the response. I actually wasn't aware of `ghc-heap` so I'll take a look at it. Oh, and by "basic support" I just meant something like "minimal requirements for building this package with GHC 8.6".

**Comment by nomeata** [comment]
Thanks! If you are motivated, yes, please check if either `ghc-heap` serves you directly (and we can deprecate `ghc-heap-view`), or if `ghc-heap-view` provides some higher level features that should be based on `ghc-heap` on GHC-8.6 and later.

**Comment by intricate** [comment]
We ended up utilizing `ghc-heap`. Thanks again, @nomeata!

**Pull request closed without merging**
